name: tripflut
description: A trip itinerary app made by Flutter.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.17
  device_preview: ^1.1.0
  go_router: ^6.0.3
  hooks_riverpod: ^2.1.3
  auto_size_text: ^3.0.0
  intl: ^0.17.0
  dynamic_color: ^1.6.2
  flutter_adaptive_scaffold: ^0.1.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  adaptive_breakpoints: ^0.1.6
  adaptive_components: ^0.0.9
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
