name: tripflut
description: A trip itinerary app made by Flutter.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.17
  device_preview: ^1.1.0
  go_router: ^6.0.3
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.1.3
  riverpod_annotation: ^1.1.1
  auto_size_text: ^3.0.0
  intl: ^0.17.0
  dynamic_color: ^1.6.2
  flutter_adaptive_scaffold: ^0.1.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  adaptive_breakpoints: ^0.1.6
  adaptive_components: ^0.0.9
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  hexcolor: ^3.0.1
  responsive_grid_list: ^1.3.1
  animations: ^2.0.7
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^1.1.1

flutter:
  uses-material-design: true
  generate: true
